#api格式版本。当前最新是v1alpha1
apiVersion: v1
kind: Pod
metadata:
  #该服务的标识符。在给定库中必须唯一。
  name: eureka
  labels:
    app: eureka
  namespace: eureka
spec:
  #容器   cgoup设置
  containers:
    - image: eureka
      name: eureka
      resources:
        requests:
          cpu: "300m"     #CPU请求，可以超过
          memory: "56Mi"  #内存请求，可以超过；但如果超过，容器可能会在Node内存不足时清理
        limits:
          cpu: "500m"    #CPU上限，可以短暂超过，容器也不会被停止
          memory: "128Mi"   #内存上限，不可以超过；如果超过，容器可能会被停止或调度到其他资源充足的机器上