spring:
  application:
    name: zuul

zuul:
  sensitiveHeaders: Authorization
  ignored-headers: Access-Control-Allow-Credentials,Access-Control-Allow-Origin,Vary,X-Frame-Options
  routes:
    authorized:
      path: /authorized/**
      serviceId: authorized
      stripPrefix: false
    zipkin:
      path: /zipkin/**
      serviceId: zipkin

