server:
  port: 80

spring:
  application:
    name: zuul-server
  profiles:
    active: eureka,route,security,zipkin

zuul:
  sensitiveHeaders: Authorization
  ignored-headers: Access-Control-Allow-Credentials,Access-Control-Allow-Origin,Vary,X-Frame-Options
  routes:
    authorized:
      path: /**
      serviceId: zuul