zuul:
  routes:
    authorized:
      path: /authorized/**
      serviceId: authorized
      stripPrefix: false
      sensitiveHeaders:
    zipkin:
      path: /zipkin/**
      serviceId: zipkin
      stripPrefix: false
      sensitiveHeaders:

ribbon:
  okhttp:
    enabled: true