spring:
  application:
    name: eurekaServer-2

server:
  port: 21002

eureka:
  instance:
    hostname: eureka-2
  client:
    serviceUrl:
      defaultZone: http://eureka-1:21001/eureka/,http://eureka-3:21003/eureka/