server:
  port: 21001

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: eureka
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    use-read-only-response-cache: true   #是否可以使用读取缓存
    initial-capacity-of-response-cache: 1000  #注册表一级guava缓存的初始大小
    response-cache-auto-expiration-in-seconds:  180  #一级缓存过期时间
    response-cache-update-interval-ms:  30000 #读写缓存更新到只读缓存