spring:
  application:
    name: eurekaServer-2

server:
  port: 8762

eureka:
  instance:
    hostname: eureka-2
  client:
    serviceUrl:
      defaultZone: http://eureka-1:8761/eureka/,http://eureka-3:8763/eureka/