spring:
  application:
    name: eurekaServer-3

server:
  port: 21003

eureka:
  instance:
    hostname: eureka-3
  client:
    serviceUrl:
      defaultZone: http://eureka-1:21001/eureka/,http://eureka-2:21002/eureka/