server:
  port: 21001

spring:
  application:
    name: eurekaServer-1

eureka:
  instance:
    hostname: eureka-1
  client:
    serviceUrl:
      defaultZone: http://eureka-2:21002/eureka/,http://eureka-3:21003/eureka/
  server:
    use-read-only-response-cache: true   #是否可以使用读取缓存
    initial-capacity-of-response-cache: 1000  #注册表一级guava缓存的初始大小
    response-cache-auto-expiration-in-seconds:  180  #一级缓存过期时间
    response-cache-update-interval-ms:  30000 #读写缓存更新到只读缓存
      defaultZone: http://eureka-2:21002/eureka/,http://eureka-3:21003/eureka/
  server:
    expected-client-renewal-interval-seconds: 30
    renewal-percent-threshold: 0.85