spring:
  application:
    name: eurekaServer-3

server:
  port: 8763

eureka:
  instance:
    hostname: eureka-3
  client:
    serviceUrl:
      defaultZone: http://eureka-1:8761/eureka/,http://eureka-2:8762/eureka/