spring:
  cloud:
    gateway:
      routes:
        - id: authorized
          uri: lb://authorized
          predicates:
            - Path=/authorized/**
          filters:
            - StripPrefix= 1
            - name: Hystrix
              args:
                name: authHystrixCommand
                fallbackUri: forward:/hystrixTimeOut
            - name: Retry
              args:
                retries: 3
                status: 404
                statusSeries: 500
        - id:  admin
          uri: lb://admin
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix= 1
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "https://docs.spring.io"
            allowedMethods:
              - GET