spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://authorized
          predicates:
            - Path=/authorized/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "https://docs.spring.io"
            allowedMethods:
              - GET