security:
  oauth2:
    client:
      accessTokenUri: http://localhost:18881/authserver/oauth/token
      userAuthorizationUri: http://localhost:18881/authserver/oauth/authorize
      clientId: client
      clientSecret: 123456
    resource:
      userInfoUri: http://localhost:9000/user