security:
  oauth2:
    client:
      accessTokenUri: http://localhost:22001/authorized/oauth/token
      userAuthorizationUri: http://localhost:22001/authorized/oauth/authorize
      clientId: route
      clientSecret: 123456
      scope: server
      grant-type: client_credentials
    resource:
      userInfoUri: http://localhost:22001/authorized/user
      preferTokenInfo: false
      jwt:
        key-uri: jwt