security:
  oauth2:
    client:
      accessTokenUri: http://localhost:7070/authserver/oauth/token
      userAuthorizationUri: http://localhost:7070/authserver/oauth/authorize
      clientId: user
      clientSecret: passwordforauthserver
    resource:
      userInfoUri: http://localhost:9000/user