security:
  oauth2:
    client:
      scope: server
      client-id: route
      client-secret: 123456
      access-token-uri: http://localhost:22001/authorized/oauth/token
      user-authorization-uri: http://localhost:22001/authorized/oauth/authorize
    resource:
      user-info-uri: http://localhost:22001/authorized/user
      prefer-token-info: false
      jwt:
        key-valuel: jwt