security:
  oauth2:
    client:
      accessTokenUri: http://localhost:22001/authorized/oauth/token
      userAuthorizationUri: http://localhost:22001/authorized/oauth/authorize
      clientId: client
      clientSecret: 123456
    resource:
      userInfoUri: http://localhost:22001/authorized/user